//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<THONGTINKHACHHANG> THONGTINKHACHHANGs { get; set; }
        public virtual DbSet<ThongTinGiaTien> ThongTinGiaTiens { get; set; }
        public virtual DbSet<Thong_Tin_Phuong_Tien> Thong_Tin_Phuong_Tiens { get; set; }
        public virtual DbSet<Thong_Tin_Ve> Thong_Tin_Ves { get; set; }
        public virtual DbSet<Thong_Tin_Ve_2> Thong_Tin_Ve_2 { get; set; }
    }
}
