//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thong_Tin_Ve_2
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<int> Gia_Tien { get; set; }
    }
}
