
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WindowsFormsApplication1
{

using System;
    using System.Collections.Generic;
    
public partial class THONGTINKHACHHANG
{

    public int Số_Thứ_Tự { get; set; }

    public string ID { get; set; }

    public string Họ { get; set; }

    public string Tên_lót { get; set; }

    public string Tên { get; set; }

    public string Địa_chỉ { get; set; }

    public Nullable<int> Mã_vùng { get; set; }

    public string Số_Điện_Thoại { get; set; }

    public string Khởi_hành { get; set; }

    public string Nơi_đến { get; set; }

    public string Phương_Tiện { get; set; }

    public string Loại_vé { get; set; }

    public string Người_sử_dụng { get; set; }

    public Nullable<int> Số_lượng { get; set; }

    public Nullable<int> Tiền { get; set; }

}

}
